"""empty message

Revision ID: 14e2624f8880
Revises: 25512f986a48
Create Date: 2024-06-06 08:48:44.811589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e2624f8880'
down_revision = '25512f986a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activation', schema=None) as batch_op:
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###
