"""empty message

Revision ID: 25512f986a48
Revises: 0f6c67a843c2
Create Date: 2024-06-05 12:54:36.318504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25512f986a48'
down_revision = '0f6c67a843c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('km_allowance', sa.Integer(), nullable=True),
    sa.Column('hour_allowance', sa.Time(), nullable=True),
    sa.Column('activation_value', sa.Float(), nullable=True),
    sa.Column('km_excess_value', sa.Float(), nullable=True),
    sa.Column('excess_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('plates', sa.String(length=50), nullable=True),
    sa.Column('agents', sa.String(length=50), nullable=True),
    sa.Column('equipment_id', sa.String(length=50), nullable=True),
    sa.Column('initial_km', sa.Integer(), nullable=True),
    sa.Column('final_km', sa.Integer(), nullable=True),
    sa.Column('toll', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('equipment_id',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('equipment_ccid',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('equipment_stock', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('reactivation', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.TEXT(length=20),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('client',
               existing_type=sa.TEXT(length=120),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('reactivation_reason',
               existing_type=sa.TEXT(length=120),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('request_channel',
               existing_type=sa.TEXT(length=90),
               type_=sa.String(length=90),
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('total_value',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactivation', schema=None) as batch_op:
        batch_op.alter_column('total_value',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=False)
        batch_op.alter_column('request_channel',
               existing_type=sa.String(length=90),
               type_=sa.TEXT(length=90),
               existing_nullable=False)
        batch_op.alter_column('reactivation_reason',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(length=120),
               existing_nullable=False)
        batch_op.alter_column('client',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(length=120),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(length=20),
               existing_nullable=True)

    with op.batch_alter_table('equipment_stock', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=True)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('equipment_ccid',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)
        batch_op.alter_column('equipment_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)

    op.drop_table('activation')
    op.drop_table('provider')
    # ### end Alembic commands ###
