"""empty message

Revision ID: 865dec71f66c
Revises: 05f8c1141797
Create Date: 2024-06-12 09:15:58.412032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865dec71f66c'
down_revision = '05f8c1141797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_timestamp')

    op.drop_table('notification')
    with op.batch_alter_table('activation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('client_toll', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_client_id', 'client', ['client_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('unread_notifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unread_notifications', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('activation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_client_id', type_='foreignkey')
        batch_op.drop_column('client_toll')
        batch_op.drop_column('client_id')

    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('viewed', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
