"""empty message

Revision ID: 86a280ad0fd2
Revises: db0f0c25eca6
Create Date: 2024-06-06 16:55:25.743845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a280ad0fd2'
down_revision = 'db0f0c25eca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('km_allowance', sa.Integer(), nullable=True),
    sa.Column('hour_allowance', sa.Time(), nullable=True),
    sa.Column('activation_value', sa.Float(), nullable=True),
    sa.Column('km_excess_value', sa.Float(), nullable=True),
    sa.Column('excess_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
