"""migrate entrance

Revision ID: bd287a9bc7f2
Revises: d95d467697f4
Create Date: 2024-05-21 12:01:43.424341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd287a9bc7f2'
down_revision = 'd95d467697f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('returned_equipment_numbers', sa.String(length=200), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('returned_equipment_numbers')
        batch_op.drop_column('maintenance_status')

    # ### end Alembic commands ###
