"""mensagem da migração

Revision ID: d95d467697f4
Revises: 6e7eadcfe3b7
Create Date: 2024-05-20 10:27:51.317333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95d467697f4'
down_revision = '6e7eadcfe3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reactivation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('client', sa.String(length=120), nullable=False),
    sa.Column('reactivation_reason', sa.String(length=120), nullable=False),
    sa.Column('request_channel', sa.String(length=90), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('total_value', sa.String(length=50), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reactivation_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.String(length=100), nullable=False),
    sa.Column('equipment_ccid', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['reactivation_id'], ['reactivation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    op.drop_table('reactivation')
    # ### end Alembic commands ###
